<?php

use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
*/

Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});

/*
*Start Api Routes For CbeInfoLocationFromController   Generated By Crud Generator  At Saturday 23rd of February 2019 12:47:57 PM
*/
Route::get('/cbeInfoLocationFroms',  'CbeInfoLocationFromController@index')->name('cbeInfoLocationFroms.index');
Route::post('/cbeInfoLocationFroms',  'CbeInfoLocationFromController@store')->name('cbeInfoLocationFroms.store');
Route::get('/cbeInfoLocationFroms/{cbeInfoLocationFrom}',  'CbeInfoLocationFromController@show')->name('cbeInfoLocationFroms.show');
Route::put('/cbeInfoLocationFroms/{cbeInfoLocationFrom}',  'CbeInfoLocationFromController@update')->name('cbeInfoLocationFroms.update');
Route::delete('/cbeInfoLocationFroms/{cbeInfoLocationFrom}',  'CbeInfoLocationFromController@destroy')->name('cbeInfoLocationFroms.destroy');
/*
*End Api Routes For CbeInfoLocationFromController
*/

/*
*Start Api Routes For CbeInfoLocationFromController   Generated By Crud Generator  At Saturday 23rd of February 2019 12:48:26 PM
*/
Route::get('/cbeInfoLocationFroms',  'CbeInfoLocationFromController@index')->name('cbeInfoLocationFroms.index');
Route::post('/cbeInfoLocationFroms',  'CbeInfoLocationFromController@store')->name('cbeInfoLocationFroms.store');
Route::get('/cbeInfoLocationFroms/{cbeInfoLocationFrom}',  'CbeInfoLocationFromController@show')->name('cbeInfoLocationFroms.show');
Route::put('/cbeInfoLocationFroms/{cbeInfoLocationFrom}',  'CbeInfoLocationFromController@update')->name('cbeInfoLocationFroms.update');
Route::delete('/cbeInfoLocationFroms/{cbeInfoLocationFrom}',  'CbeInfoLocationFromController@destroy')->name('cbeInfoLocationFroms.destroy');
/*
*End Api Routes For CbeInfoLocationFromController
*/

/*
*Start Api Routes For CbeInfoLocationToController   Generated By Crud Generator  At Saturday 23rd of February 2019 05:37:57 PM
*/
Route::get('/cbeInfoLocationTos',  'CbeInfoLocationToController@index')->name('cbeInfoLocationTos.index');
Route::post('/cbeInfoLocationTos',  'CbeInfoLocationToController@store')->name('cbeInfoLocationTos.store');
Route::get('/cbeInfoLocationTos/{cbeInfoLocationTo}',  'CbeInfoLocationToController@show')->name('cbeInfoLocationTos.show');
Route::put('/cbeInfoLocationTos/{cbeInfoLocationTo}',  'CbeInfoLocationToController@update')->name('cbeInfoLocationTos.update');
Route::delete('/cbeInfoLocationTos/{cbeInfoLocationTo}',  'CbeInfoLocationToController@destroy')->name('cbeInfoLocationTos.destroy');
/*
*End Api Routes For CbeInfoLocationToController
*/

/*
*Start Api Routes For CbeInfoLocationToController   Generated By Crud Generator  At Saturday 23rd of February 2019 05:47:58 PM
*/
Route::get('/cbeInfoLocationTos',  'CbeInfoLocationToController@index')->name('cbeInfoLocationTos.index');
Route::post('/cbeInfoLocationTos',  'CbeInfoLocationToController@store')->name('cbeInfoLocationTos.store');
Route::get('/cbeInfoLocationTos/{cbeInfoLocationTo}',  'CbeInfoLocationToController@show')->name('cbeInfoLocationTos.show');
Route::put('/cbeInfoLocationTos/{cbeInfoLocationTo}',  'CbeInfoLocationToController@update')->name('cbeInfoLocationTos.update');
Route::delete('/cbeInfoLocationTos/{cbeInfoLocationTo}',  'CbeInfoLocationToController@destroy')->name('cbeInfoLocationTos.destroy');
/*
*End Api Routes For CbeInfoLocationToController
*/

/*
*Start Api Routes For CbeInfoLocationToController   Generated By Crud Generator  At Saturday 23rd of February 2019 05:50:13 PM
*/
Route::get('/cbeInfoLocationTos',  'CbeInfoLocationToController@index')->name('cbeInfoLocationTos.index');
Route::post('/cbeInfoLocationTos',  'CbeInfoLocationToController@store')->name('cbeInfoLocationTos.store');
Route::get('/cbeInfoLocationTos/{cbeInfoLocationTo}',  'CbeInfoLocationToController@show')->name('cbeInfoLocationTos.show');
Route::put('/cbeInfoLocationTos/{cbeInfoLocationTo}',  'CbeInfoLocationToController@update')->name('cbeInfoLocationTos.update');
Route::delete('/cbeInfoLocationTos/{cbeInfoLocationTo}',  'CbeInfoLocationToController@destroy')->name('cbeInfoLocationTos.destroy');
/*
*End Api Routes For CbeInfoLocationToController
*/

/*
*Start Api Routes For CbeInfoLocationToController   Generated By Crud Generator  At Saturday 23rd of February 2019 05:50:33 PM
*/
Route::get('/cbeInfoLocationTos',  'CbeInfoLocationToController@index')->name('cbeInfoLocationTos.index');
Route::post('/cbeInfoLocationTos',  'CbeInfoLocationToController@store')->name('cbeInfoLocationTos.store');
Route::get('/cbeInfoLocationTos/{cbeInfoLocationTo}',  'CbeInfoLocationToController@show')->name('cbeInfoLocationTos.show');
Route::put('/cbeInfoLocationTos/{cbeInfoLocationTo}',  'CbeInfoLocationToController@update')->name('cbeInfoLocationTos.update');
Route::delete('/cbeInfoLocationTos/{cbeInfoLocationTo}',  'CbeInfoLocationToController@destroy')->name('cbeInfoLocationTos.destroy');
/*
*End Api Routes For CbeInfoLocationToController
*/

/*
*Start Api Routes For CbeInfoLocationToController   Generated By Crud Generator  At Saturday 23rd of February 2019 05:51:10 PM
*/
Route::get('/cbeInfoLocationTos',  'CbeInfoLocationToController@index')->name('cbeInfoLocationTos.index');
Route::post('/cbeInfoLocationTos',  'CbeInfoLocationToController@store')->name('cbeInfoLocationTos.store');
Route::get('/cbeInfoLocationTos/{cbeInfoLocationTo}',  'CbeInfoLocationToController@show')->name('cbeInfoLocationTos.show');
Route::put('/cbeInfoLocationTos/{cbeInfoLocationTo}',  'CbeInfoLocationToController@update')->name('cbeInfoLocationTos.update');
Route::delete('/cbeInfoLocationTos/{cbeInfoLocationTo}',  'CbeInfoLocationToController@destroy')->name('cbeInfoLocationTos.destroy');
/*
*End Api Routes For CbeInfoLocationToController
*/

/*
*Start Api Routes For CbeInfoLocationToController   Generated By Crud Generator  At Saturday 23rd of February 2019 05:53:44 PM
*/
Route::get('/cbeInfoLocationTos',  'CbeInfoLocationToController@index')->name('cbeInfoLocationTos.index');
Route::post('/cbeInfoLocationTos',  'CbeInfoLocationToController@store')->name('cbeInfoLocationTos.store');
Route::get('/cbeInfoLocationTos/{cbeInfoLocationTo}',  'CbeInfoLocationToController@show')->name('cbeInfoLocationTos.show');
Route::put('/cbeInfoLocationTos/{cbeInfoLocationTo}',  'CbeInfoLocationToController@update')->name('cbeInfoLocationTos.update');
Route::delete('/cbeInfoLocationTos/{cbeInfoLocationTo}',  'CbeInfoLocationToController@destroy')->name('cbeInfoLocationTos.destroy');
/*
*End Api Routes For CbeInfoLocationToController
*/

/*
*Start Api Routes For CbeInfoBusNameController   Generated By Crud Generator  At Saturday 23rd of February 2019 06:33:18 PM
*/
Route::get('/cbeInfoBusNames',  'CbeInfoBusNameController@index')->name('cbeInfoBusNames.index');
Route::post('/cbeInfoBusNames',  'CbeInfoBusNameController@store')->name('cbeInfoBusNames.store');
Route::get('/cbeInfoBusNames/{cbeInfoBusName}',  'CbeInfoBusNameController@show')->name('cbeInfoBusNames.show');
Route::put('/cbeInfoBusNames/{cbeInfoBusName}',  'CbeInfoBusNameController@update')->name('cbeInfoBusNames.update');
Route::delete('/cbeInfoBusNames/{cbeInfoBusName}',  'CbeInfoBusNameController@destroy')->name('cbeInfoBusNames.destroy');
/*
*End Api Routes For CbeInfoBusNameController
*/

/*
*Start Api Routes For CbeInfoBusTypeController   Generated By Crud Generator  At Saturday 23rd of February 2019 06:37:17 PM
*/
Route::get('/cbeInfoBusTypes',  'CbeInfoBusTypeController@index')->name('cbeInfoBusTypes.index');
Route::post('/cbeInfoBusTypes',  'CbeInfoBusTypeController@store')->name('cbeInfoBusTypes.store');
Route::get('/cbeInfoBusTypes/{cbeInfoBusType}',  'CbeInfoBusTypeController@show')->name('cbeInfoBusTypes.show');
Route::put('/cbeInfoBusTypes/{cbeInfoBusType}',  'CbeInfoBusTypeController@update')->name('cbeInfoBusTypes.update');
Route::delete('/cbeInfoBusTypes/{cbeInfoBusType}',  'CbeInfoBusTypeController@destroy')->name('cbeInfoBusTypes.destroy');
/*
*End Api Routes For CbeInfoBusTypeController
*/

/*
*Start Api Routes For CbeInfoBusViaController   Generated By Crud Generator  At Saturday 23rd of February 2019 08:49:09 PM
*/
Route::get('/cbeInfoBusVias',  'CbeInfoBusViaController@index')->name('cbeInfoBusVias.index');
Route::post('/cbeInfoBusVias',  'CbeInfoBusViaController@store')->name('cbeInfoBusVias.store');
Route::get('/cbeInfoBusVias/{cbeInfoBusVia}',  'CbeInfoBusViaController@show')->name('cbeInfoBusVias.show');
Route::put('/cbeInfoBusVias/{cbeInfoBusVia}',  'CbeInfoBusViaController@update')->name('cbeInfoBusVias.update');
Route::delete('/cbeInfoBusVias/{cbeInfoBusVia}',  'CbeInfoBusViaController@destroy')->name('cbeInfoBusVias.destroy');
/*
*End Api Routes For CbeInfoBusViaController
*/

/*
*Start Api Routes For CbeInfoBusTimingController   Generated By Crud Generator  At Saturday 23rd of February 2019 10:01:45 PM
*/
Route::get('/cbeInfoBusTimings',  'CbeInfoBusTimingController@index')->name('cbeInfoBusTimings.index');
Route::post('/cbeInfoBusTimings',  'CbeInfoBusTimingController@store')->name('cbeInfoBusTimings.store');
Route::get('/cbeInfoBusTimings/{cbeInfoBusTiming}',  'CbeInfoBusTimingController@show')->name('cbeInfoBusTimings.show');
Route::put('/cbeInfoBusTimings/{cbeInfoBusTiming}',  'CbeInfoBusTimingController@update')->name('cbeInfoBusTimings.update');
Route::delete('/cbeInfoBusTimings/{cbeInfoBusTiming}',  'CbeInfoBusTimingController@destroy')->name('cbeInfoBusTimings.destroy');
/*
*End Api Routes For CbeInfoBusTimingController
*/
