<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Auth::routes();
Auth::routes(['register' => false]);

Route::get('/', 'SiteController@landingPage')->name('site.landing');
Route::get('/home', 'HomeController@index')->name('home');



/*
*Start Web Routes For CbeInfoLocationFromController   Generated By Crud Generator  At Saturday 23rd of February 2019 12:48:26 PM
*/
Route::get('/cbeInfoLocationFroms',  'CbeInfoLocationFromController@index')->name('cbeInfoLocationFroms.index');
Route::get('/cbeInfoLocationFroms/create',  'CbeInfoLocationFromController@create')->name('cbeInfoLocationFroms.create');
Route::post('/cbeInfoLocationFroms',  'CbeInfoLocationFromController@store')->name('cbeInfoLocationFroms.store');
Route::get('/cbeInfoLocationFroms/{cbeInfoLocationFrom}',  'CbeInfoLocationFromController@show')->name('cbeInfoLocationFroms.show');
Route::get('/cbeInfoLocationFroms/{cbeInfoLocationFrom}/edit',  'CbeInfoLocationFromController@edit')->name('cbeInfoLocationFroms.edit');
Route::put('/cbeInfoLocationFroms/{cbeInfoLocationFrom}',  'CbeInfoLocationFromController@update')->name('cbeInfoLocationFroms.update');
Route::delete('/cbeInfoLocationFroms/{cbeInfoLocationFrom}',  'CbeInfoLocationFromController@destroy')->name('cbeInfoLocationFroms.destroy');
/*
*End Web Routes For CbeInfoLocationFromController
*/

/*
*Start Web Routes For CbeInfoLocationToController   Generated By Crud Generator  At Saturday 23rd of February 2019 05:37:57 PM
*/
Route::get('/cbeInfoLocationTos',  'CbeInfoLocationToController@index')->name('cbeInfoLocationTos.index');
Route::get('/cbeInfoLocationTos/create',  'CbeInfoLocationToController@create')->name('cbeInfoLocationTos.create');
Route::post('/cbeInfoLocationTos',  'CbeInfoLocationToController@store')->name('cbeInfoLocationTos.store');
Route::get('/cbeInfoLocationTos/{cbeInfoLocationTo}',  'CbeInfoLocationToController@show')->name('cbeInfoLocationTos.show');
Route::get('/cbeInfoLocationTos/{cbeInfoLocationTo}/edit',  'CbeInfoLocationToController@edit')->name('cbeInfoLocationTos.edit');
Route::put('/cbeInfoLocationTos/{cbeInfoLocationTo}',  'CbeInfoLocationToController@update')->name('cbeInfoLocationTos.update');
Route::delete('/cbeInfoLocationTos/{cbeInfoLocationTo}',  'CbeInfoLocationToController@destroy')->name('cbeInfoLocationTos.destroy');
/*
*End Web Routes For CbeInfoLocationToController
*/
/*
*Start Web Routes For CbeInfoBusNameController   Generated By Crud Generator  At Saturday 23rd of February 2019 06:33:18 PM
*/
Route::get('/cbeInfoBusNames',  'CbeInfoBusNameController@index')->name('cbeInfoBusNames.index');
Route::get('/cbeInfoBusNames/create',  'CbeInfoBusNameController@create')->name('cbeInfoBusNames.create');
Route::post('/cbeInfoBusNames',  'CbeInfoBusNameController@store')->name('cbeInfoBusNames.store');
Route::get('/cbeInfoBusNames/{cbeInfoBusName}',  'CbeInfoBusNameController@show')->name('cbeInfoBusNames.show');
Route::get('/cbeInfoBusNames/{cbeInfoBusName}/edit',  'CbeInfoBusNameController@edit')->name('cbeInfoBusNames.edit');
Route::put('/cbeInfoBusNames/{cbeInfoBusName}',  'CbeInfoBusNameController@update')->name('cbeInfoBusNames.update');
Route::delete('/cbeInfoBusNames/{cbeInfoBusName}',  'CbeInfoBusNameController@destroy')->name('cbeInfoBusNames.destroy');
/*
*End Web Routes For CbeInfoBusNameController
*/

/*
*Start Web Routes For CbeInfoBusTypeController   Generated By Crud Generator  At Saturday 23rd of February 2019 06:37:17 PM
*/
Route::get('/cbeInfoBusTypes',  'CbeInfoBusTypeController@index')->name('cbeInfoBusTypes.index');
Route::get('/cbeInfoBusTypes/create',  'CbeInfoBusTypeController@create')->name('cbeInfoBusTypes.create');
Route::post('/cbeInfoBusTypes',  'CbeInfoBusTypeController@store')->name('cbeInfoBusTypes.store');
Route::get('/cbeInfoBusTypes/{cbeInfoBusType}',  'CbeInfoBusTypeController@show')->name('cbeInfoBusTypes.show');
Route::get('/cbeInfoBusTypes/{cbeInfoBusType}/edit',  'CbeInfoBusTypeController@edit')->name('cbeInfoBusTypes.edit');
Route::put('/cbeInfoBusTypes/{cbeInfoBusType}',  'CbeInfoBusTypeController@update')->name('cbeInfoBusTypes.update');
Route::delete('/cbeInfoBusTypes/{cbeInfoBusType}',  'CbeInfoBusTypeController@destroy')->name('cbeInfoBusTypes.destroy');
/*
*End Web Routes For CbeInfoBusTypeController
*/

/*
*Start Web Routes For CbeInfoBusViaController   Generated By Crud Generator  At Saturday 23rd of February 2019 08:49:09 PM
*/
Route::get('/cbeInfoBusVias',  'CbeInfoBusViaController@index')->name('cbeInfoBusVias.index');
Route::get('/cbeInfoBusVias/create',  'CbeInfoBusViaController@create')->name('cbeInfoBusVias.create');
Route::post('/cbeInfoBusVias',  'CbeInfoBusViaController@store')->name('cbeInfoBusVias.store');
Route::get('/cbeInfoBusVias/{cbeInfoBusVia}',  'CbeInfoBusViaController@show')->name('cbeInfoBusVias.show');
Route::get('/cbeInfoBusVias/{cbeInfoBusVia}/edit',  'CbeInfoBusViaController@edit')->name('cbeInfoBusVias.edit');
Route::put('/cbeInfoBusVias/{cbeInfoBusVia}',  'CbeInfoBusViaController@update')->name('cbeInfoBusVias.update');
Route::delete('/cbeInfoBusVias/{cbeInfoBusVia}',  'CbeInfoBusViaController@destroy')->name('cbeInfoBusVias.destroy');
/*
*End Web Routes For CbeInfoBusViaController
*/

/*
*Start Web Routes For CbeInfoBusTimingController   Generated By Crud Generator  At Saturday 23rd of February 2019 10:01:45 PM
*/
Route::get('/cbeInfoBusTimings',  'CbeInfoBusTimingController@index')->name('cbeInfoBusTimings.index');
Route::get('/cbeInfoBusTimings/create',  'CbeInfoBusTimingController@create')->name('cbeInfoBusTimings.create');
Route::post('/cbeInfoBusTimings',  'CbeInfoBusTimingController@store')->name('cbeInfoBusTimings.store');
Route::get('/cbeInfoBusTimings/{cbeInfoBusTiming}',  'CbeInfoBusTimingController@show')->name('cbeInfoBusTimings.show');
Route::get('/cbeInfoBusTimings/{cbeInfoBusTiming}/edit',  'CbeInfoBusTimingController@edit')->name('cbeInfoBusTimings.edit');
Route::put('/cbeInfoBusTimings/{cbeInfoBusTiming}',  'CbeInfoBusTimingController@update')->name('cbeInfoBusTimings.update');
Route::delete('/cbeInfoBusTimings/{cbeInfoBusTiming}',  'CbeInfoBusTimingController@destroy')->name('cbeInfoBusTimings.destroy');
/*
*End Web Routes For CbeInfoBusTimingController
*/
Route::any('/search/busses/{page?}','SiteController@serachBus')->name('search.busses');

// Route::any('/search/docDocuments', 'DocDocumentController@searchDocuments')->name('docDocuments.searchDocuments');
